# Week 7 Videos

## Trying to use linear regression for classification

<iframe width="560" height="315" src="https://www.youtube.com/embed/2F1CIww84k8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

With respect to the *penguins* dataset, write a linear function to model the following.
* Input: bill length
* Output: 1 if the species is "Adelie", 0 otherwise

In [ ]:
import numpy as np
import pandas as pd
import altair as alt
import seaborn as sns

In [ ]:
df = sns.load_dataset("penguins").dropna()

In [ ]:
df["isAdelie_bool"] = (df["species"] == "Adelie")

In [ ]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  isAdelie_bool  
0       3750.0    Male           True  
1       3800.0  Female           True  
2       3250.0  Female           True  
4       3450.0  Female           True  
5       3650.0    Male           True

In [ ]:
(df["species"] == "Adelie")

0       True
1       True
2       True
4       True
5       True
       ...  
338    False
340    False
341    False
342    False
343    False
Name: species, Length: 333, dtype: bool

In [ ]:
(df["species"] == "Adelie").astype(float)

0      1.0
1      1.0
2      1.0
4      1.0
5      1.0
      ... 
338    0.0
340    0.0
341    0.0
342    0.0
343    0.0
Name: species, Length: 333, dtype: float64

In [ ]:
df["isAdelie_float"] = (df["species"] == "Adelie").astype(float)

In [ ]:
df.tail()

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
338  Gentoo  Biscoe            47.2           13.7              214.0   
340  Gentoo  Biscoe            46.8           14.3              215.0   
341  Gentoo  Biscoe            50.4           15.7              222.0   
342  Gentoo  Biscoe            45.2           14.8              212.0   
343  Gentoo  Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  isAdelie_bool  isAdelie_float  
338       4925.0  Female          False             0.0  
340       4850.0  Female          False             0.0  
341       5750.0    Male          False             0.0  
342       5200.0  Female          False             0.0  
343       5400.0    Male          False             0.0

In [ ]:
alt.Chart(df).mark_circle().encode(
    x="bill_length_mm",
    y="isAdelie_bool"
)

alt.Chart(...)

In [ ]:
alt.Chart(df).mark_circle().encode(
    x="bill_length_mm",
    y="isAdelie_float"
)

alt.Chart(...)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
reg = LinearRegression()

In [ ]:
reg.fit(df[["bill_length_mm"]], df["isAdelie_float"])

LinearRegression()

In [ ]:
c = alt.Chart(df).mark_circle().encode(
    x="bill_length_mm",
    y="isAdelie_float"
)

In [ ]:
df["Pred"] = reg.predict(df[["bill_length_mm"]])

In [ ]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  isAdelie_bool  isAdelie_float      Pred  
0       3750.0    Male           True             1.0  0.810316  
1       3800.0  Female           True             1.0  0.779914  
2       3250.0  Female           True             1.0  0.719110  
4       3450.0  Female           True             1.0  0.992728  
5       3650.0    Male           True             1.0  0.795115

In [ ]:
c1 = alt.Chart(df).mark_line(color="red").encode(
    x="bill_length_mm",
    y="Pred"
)

In [ ]:
c+c1

alt.LayerChart(...)

## Logistic Regression, Part 1

<iframe width="560" height="315" src="https://www.youtube.com/embed/NBY7SDsTH0E" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
clf = LogisticRegression()

In [ ]:
clf.fit(df[["bill_length_mm"]], df["isAdelie_float"])

LogisticRegression()

In [ ]:
df["Pred2"] = clf.predict(df[["bill_length_mm"]])

In [ ]:
c2 = alt.Chart(df).mark_point(color="red").encode(
    x="bill_length_mm",
    y="Pred2"
)

In [ ]:
c+c2

alt.LayerChart(...)

## Logistic Regression, Part 2

<iframe width="560" height="315" src="https://www.youtube.com/embed/lufySby-TJ0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [ ]:
clf.predict(df[["bill_length_mm"]])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0.

In [ ]:
clf.classes_

array([0., 1.])

In [ ]:
clf.predict_proba(df[["bill_length_mm"]])

array([[1.30799652e-02, 9.86920035e-01],
       [2.05066613e-02, 9.79493339e-01],
       [4.96495104e-02, 9.50350490e-01],
       [8.52199486e-04, 9.99147801e-01],
       [1.63845452e-02, 9.83615455e-01],
       [1.04348115e-02, 9.89565189e-01],
       [1.46406871e-02, 9.85359313e-01],
       [1.15331850e-01, 8.84668150e-01],
       [7.42806258e-03, 9.92571937e-01],
       [7.73377420e-05, 9.99922662e-01],
       [7.60219551e-04, 9.99239780e-01],
       [8.32007603e-03, 9.91679924e-01],
       [3.92426682e-01, 6.07573318e-01],
       [6.15338273e-05, 9.99938466e-01],
       [9.72443311e-01, 2.75566890e-02],
       [2.99002877e-03, 9.97009971e-01],
       [2.66792391e-03, 9.97332076e-01],
       [3.41684610e-04, 9.99658315e-01],
       [4.71511319e-03, 9.95284887e-01],
       [9.31820304e-03, 9.90681797e-01],
       [1.72125733e-04, 9.99827874e-01],
       [6.85661583e-02, 9.31433842e-01],
       [6.16163575e-02, 9.38383643e-01],
       [3.35089145e-03, 9.96649109e-01],
       [6.161635

In [ ]:
A = clf.predict_proba(df[["bill_length_mm"]])

In [ ]:
df["Pred3"] = A[:,1]

In [ ]:
c3 = alt.Chart(df).mark_line(color="red").encode(
    x="bill_length_mm",
    y="Pred3"
)

In [ ]:
c+c3

alt.LayerChart(...)

## Logistic Regression, Part 3

<iframe width="560" height="315" src="https://www.youtube.com/embed/nBexZhm6QHQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [ ]:
clf = LogisticRegression()

In [ ]:
clf.fit(df[["bill_length_mm"]], df["species"])

LogisticRegression()

In [ ]:
df["Pred4"] = clf.predict(df[["bill_length_mm"]])

In [ ]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  isAdelie_bool  isAdelie_float      Pred  Pred2  \
0       3750.0    Male           True             1.0  0.810316    1.0   
1       3800.0  Female           True             1.0  0.779914    1.0   
2       3250.0  Female           True             1.0  0.719110    1.0   
4       3450.0  Female           True             1.0  0.992728    1.0   
5       3650.0    Male           True             1.0  0.795115    1.0   

      Pred3   Pred4  
0  0.986920  Adelie  
1  0.979493  Adelie  
2  0.950350  Adelie  
4  0.999148  Adelie  
5  0.983615  Adelie

In [ ]:
df["Pred4"].value_counts()

Gentoo       173
Adelie       150
Chinstrap     10
Name: Pred4, dtype: int64

In [ ]:
df["species"].value_counts()

Adelie       146
Gentoo       119
Chinstrap     68
Name: species, dtype: int64

In [ ]:
alt.Chart(df).mark_circle().encode(
    x="bill_length_mm",
    y="flipper_length_mm",
    color="species"
)

alt.Chart(...)

In [ ]:
clf.score(df[["bill_length_mm"]], df["species"])

0.7537537537537538

In [ ]:
clf.classes_

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [ ]:
clf.predict_proba(df[["bill_length_mm"]])

array([[9.87130539e-01, 2.03702100e-03, 1.08324397e-02],
       [9.79823354e-01, 3.32737771e-03, 1.68492686e-02],
       [9.51091028e-01, 8.74667922e-03, 4.01622930e-02],
       [9.99155737e-01, 1.03813470e-04, 7.40449484e-04],
       [9.83879892e-01, 2.60453202e-03, 1.35155762e-02],
       [9.89731718e-01, 1.59210500e-03, 8.67617683e-03],
       [9.85595436e-01, 2.30357815e-03, 1.21009863e-02],
       [8.86053128e-01, 2.20672226e-02, 9.18796490e-02],
       [9.92687793e-01, 1.09904848e-03, 6.21315814e-03],
       [9.99922311e-01, 7.60039974e-06, 7.00890612e-05],
       [9.99246476e-01, 9.16663201e-05, 6.61857479e-04],
       [9.91810870e-01, 1.24370214e-03, 6.94542752e-03],
       [6.09053113e-01, 8.67181448e-02, 3.04228742e-01],
       [9.99938084e-01, 5.92483944e-06, 5.59907528e-05],
       [2.66195596e-02, 2.96191724e-01, 6.77188717e-01],
       [9.97051092e-01, 4.07619342e-04, 2.54128862e-03],
       [9.97367925e-01, 3.60005733e-04, 2.27206934e-03],
       [9.99659963e-01, 3.83535

In [ ]:
clf2 = LogisticRegression()

In [ ]:
clf2.fit(df[["bill_length_mm","flipper_length_mm"]], df["species"])

LogisticRegression()

In [ ]:
clf2.score(df[["bill_length_mm","flipper_length_mm"]], df["species"])

0.9579579579579579

In [ ]:
clf2.predict(df[["bill_length_mm","flipper_length_mm"]])

array(['Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Chinstrap', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Chinstrap', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',

In [ ]:
clf2.predict(df[["bill_length_mm","flipper_length_mm"]]) == df["species"]

0      True
1      True
2      True
4      True
5      True
       ... 
338    True
340    True
341    True
342    True
343    True
Name: species, Length: 333, dtype: bool

In [ ]:
(clf2.predict(df[["bill_length_mm","flipper_length_mm"]]) == df["species"]).mean()

0.9579579579579579