# Week 9 Videos

## Logistic regression decision boundary with 3 classes

<iframe width="560" height="315" src="https://www.youtube.com/embed/BDfoP8CAISE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [1]:
import altair as alt
import seaborn as sns

In [2]:
df = sns.load_dataset("penguins").dropna()

In [3]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [4]:
cols = ['bill_length_mm', 'bill_depth_mm']

In [5]:
alt.Chart(df).mark_circle().encode(
    x=alt.X(cols[0], scale=alt.Scale(zero=False)),
    y=alt.Y(cols[1], scale=alt.Scale(zero=False)),
    color="species"
)

alt.Chart(...)

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
clf = LogisticRegression()

In [8]:
clf.fit(df[cols], df["species"])

LogisticRegression()

In [9]:
df["pred"] = clf.predict(df[cols])

In [10]:
alt.Chart(df).mark_circle().encode(
    x=alt.X(cols[0], scale=alt.Scale(zero=False)),
    y=alt.Y(cols[1], scale=alt.Scale(zero=False)),
    color="pred"
)

alt.Chart(...)

## A grid of points using NumPy

<iframe width="560" height="315" src="https://www.youtube.com/embed/JoZJuCsHJhE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [11]:
import numpy as np
import pandas as pd

In [12]:
x = np.arange(32, 60, 0.2)
y = np.arange(13, 22, 0.2)

In [13]:
pd.DataFrame({"x":x, "y":y})

ValueError: All arrays must be of the same length

In [14]:
x

array([32. , 32.2, 32.4, 32.6, 32.8, 33. , 33.2, 33.4, 33.6, 33.8, 34. ,
       34.2, 34.4, 34.6, 34.8, 35. , 35.2, 35.4, 35.6, 35.8, 36. , 36.2,
       36.4, 36.6, 36.8, 37. , 37.2, 37.4, 37.6, 37.8, 38. , 38.2, 38.4,
       38.6, 38.8, 39. , 39.2, 39.4, 39.6, 39.8, 40. , 40.2, 40.4, 40.6,
       40.8, 41. , 41.2, 41.4, 41.6, 41.8, 42. , 42.2, 42.4, 42.6, 42.8,
       43. , 43.2, 43.4, 43.6, 43.8, 44. , 44.2, 44.4, 44.6, 44.8, 45. ,
       45.2, 45.4, 45.6, 45.8, 46. , 46.2, 46.4, 46.6, 46.8, 47. , 47.2,
       47.4, 47.6, 47.8, 48. , 48.2, 48.4, 48.6, 48.8, 49. , 49.2, 49.4,
       49.6, 49.8, 50. , 50.2, 50.4, 50.6, 50.8, 51. , 51.2, 51.4, 51.6,
       51.8, 52. , 52.2, 52.4, 52.6, 52.8, 53. , 53.2, 53.4, 53.6, 53.8,
       54. , 54.2, 54.4, 54.6, 54.8, 55. , 55.2, 55.4, 55.6, 55.8, 56. ,
       56.2, 56.4, 56.6, 56.8, 57. , 57.2, 57.4, 57.6, 57.8, 58. , 58.2,
       58.4, 58.6, 58.8, 59. , 59.2, 59.4, 59.6, 59.8])

In [15]:
y

array([13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. ,
       15.2, 15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2,
       17.4, 17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4,
       19.6, 19.8, 20. , 20.2, 20.4, 20.6, 20.8, 21. , 21.2, 21.4, 21.6,
       21.8])

In [16]:
xx, yy = np.meshgrid(x,y)

In [17]:
xx

array([[32. , 32.2, 32.4, ..., 59.4, 59.6, 59.8],
       [32. , 32.2, 32.4, ..., 59.4, 59.6, 59.8],
       [32. , 32.2, 32.4, ..., 59.4, 59.6, 59.8],
       ...,
       [32. , 32.2, 32.4, ..., 59.4, 59.6, 59.8],
       [32. , 32.2, 32.4, ..., 59.4, 59.6, 59.8],
       [32. , 32.2, 32.4, ..., 59.4, 59.6, 59.8]])

In [18]:
yy

array([[13. , 13. , 13. , ..., 13. , 13. , 13. ],
       [13.2, 13.2, 13.2, ..., 13.2, 13.2, 13.2],
       [13.4, 13.4, 13.4, ..., 13.4, 13.4, 13.4],
       ...,
       [21.4, 21.4, 21.4, ..., 21.4, 21.4, 21.4],
       [21.6, 21.6, 21.6, ..., 21.6, 21.6, 21.6],
       [21.8, 21.8, 21.8, ..., 21.8, 21.8, 21.8]])

In [19]:
xx.shape

(45, 140)

In [20]:
x.size

140

In [21]:
y.size

45

In [22]:
xx.reshape(-1)

array([32. , 32.2, 32.4, ..., 59.4, 59.6, 59.8])

In [23]:
yy.reshape(-1)

array([13. , 13. , 13. , ..., 21.8, 21.8, 21.8])

In [24]:
xx.reshape(-1).size

6300

In [25]:
x.size*y.size

6300

In [26]:
df_sim = pd.DataFrame({"x":xx.reshape(-1), "y":yy.reshape(-1)})

In [27]:
df_sim

x     y
0     32.0  13.0
1     32.2  13.0
2     32.4  13.0
3     32.6  13.0
4     32.8  13.0
...    ...   ...
6295  59.0  21.8
6296  59.2  21.8
6297  59.4  21.8
6298  59.6  21.8
6299  59.8  21.8

[6300 rows x 2 columns]

In [28]:
df_sim.tail()

x     y
6295  59.0  21.8
6296  59.2  21.8
6297  59.4  21.8
6298  59.6  21.8
6299  59.8  21.8

## A grid of points using itertools

<iframe width="560" height="315" src="https://www.youtube.com/embed/-GuIKRGNVVs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [29]:
from itertools import product

In [30]:
x

array([32. , 32.2, 32.4, 32.6, 32.8, 33. , 33.2, 33.4, 33.6, 33.8, 34. ,
       34.2, 34.4, 34.6, 34.8, 35. , 35.2, 35.4, 35.6, 35.8, 36. , 36.2,
       36.4, 36.6, 36.8, 37. , 37.2, 37.4, 37.6, 37.8, 38. , 38.2, 38.4,
       38.6, 38.8, 39. , 39.2, 39.4, 39.6, 39.8, 40. , 40.2, 40.4, 40.6,
       40.8, 41. , 41.2, 41.4, 41.6, 41.8, 42. , 42.2, 42.4, 42.6, 42.8,
       43. , 43.2, 43.4, 43.6, 43.8, 44. , 44.2, 44.4, 44.6, 44.8, 45. ,
       45.2, 45.4, 45.6, 45.8, 46. , 46.2, 46.4, 46.6, 46.8, 47. , 47.2,
       47.4, 47.6, 47.8, 48. , 48.2, 48.4, 48.6, 48.8, 49. , 49.2, 49.4,
       49.6, 49.8, 50. , 50.2, 50.4, 50.6, 50.8, 51. , 51.2, 51.4, 51.6,
       51.8, 52. , 52.2, 52.4, 52.6, 52.8, 53. , 53.2, 53.4, 53.6, 53.8,
       54. , 54.2, 54.4, 54.6, 54.8, 55. , 55.2, 55.4, 55.6, 55.8, 56. ,
       56.2, 56.4, 56.6, 56.8, 57. , 57.2, 57.4, 57.6, 57.8, 58. , 58.2,
       58.4, 58.6, 58.8, 59. , 59.2, 59.4, 59.6, 59.8])

In [31]:
y

array([13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. ,
       15.2, 15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2,
       17.4, 17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4,
       19.6, 19.8, 20. , 20.2, 20.4, 20.6, 20.8, 21. , 21.2, 21.4, 21.6,
       21.8])

In [32]:
g = product(x,y)

In [33]:
type(g)

itertools.product

In [34]:
list(g)

[(32.0, 13.0),
 (32.0, 13.2),
 (32.0, 13.399999999999999),
 (32.0, 13.599999999999998),
 (32.0, 13.799999999999997),
 (32.0, 13.999999999999996),
 (32.0, 14.199999999999996),
 (32.0, 14.399999999999995),
 (32.0, 14.599999999999994),
 (32.0, 14.799999999999994),
 (32.0, 14.999999999999993),
 (32.0, 15.199999999999992),
 (32.0, 15.399999999999991),
 (32.0, 15.59999999999999),
 (32.0, 15.79999999999999),
 (32.0, 15.99999999999999),
 (32.0, 16.19999999999999),
 (32.0, 16.399999999999988),
 (32.0, 16.599999999999987),
 (32.0, 16.799999999999986),
 (32.0, 16.999999999999986),
 (32.0, 17.199999999999985),
 (32.0, 17.399999999999984),
 (32.0, 17.599999999999984),
 (32.0, 17.799999999999983),
 (32.0, 17.999999999999982),
 (32.0, 18.19999999999998),
 (32.0, 18.39999999999998),
 (32.0, 18.59999999999998),
 (32.0, 18.79999999999998),
 (32.0, 18.99999999999998),
 (32.0, 19.199999999999978),
 (32.0, 19.399999999999977),
 (32.0, 19.599999999999977),
 (32.0, 19.799999999999976),
 (32.0, 19.99999999999

In [35]:
list(g)[-5:]

[]

In [36]:
g2 = product(x,y)

In [37]:
list(g2)[-5:]

[(59.800000000000395, 20.99999999999997),
 (59.800000000000395, 21.19999999999997),
 (59.800000000000395, 21.39999999999997),
 (59.800000000000395, 21.59999999999997),
 (59.800000000000395, 21.79999999999997)]

In [38]:
g = product(x,y)

In [39]:
pd.DataFrame(g)

0     1
0     32.0  13.0
1     32.0  13.2
2     32.0  13.4
3     32.0  13.6
4     32.0  13.8
...    ...   ...
6295  59.8  21.0
6296  59.8  21.2
6297  59.8  21.4
6298  59.8  21.6
6299  59.8  21.8

[6300 rows x 2 columns]

In [40]:
cols

['bill_length_mm', 'bill_depth_mm']

In [41]:
pd.DataFrame(g, columns=cols)

Empty DataFrame
Columns: [bill_length_mm, bill_depth_mm]
Index: []

In [42]:
df_sim2 = pd.DataFrame(product(x,y), columns=cols)

In [43]:
df_sim2

bill_length_mm  bill_depth_mm
0               32.0           13.0
1               32.0           13.2
2               32.0           13.4
3               32.0           13.6
4               32.0           13.8
...              ...            ...
6295            59.8           21.0
6296            59.8           21.2
6297            59.8           21.4
6298            59.8           21.6
6299            59.8           21.8

[6300 rows x 2 columns]

## Using the grid of points to visualize the decision boundary

<iframe width="560" height="315" src="https://www.youtube.com/embed/iKZX1qEB-UM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [44]:
alt.Chart(df).mark_circle().encode(
    x=alt.X(cols[0], scale=alt.Scale(zero=False)),
    y=alt.Y(cols[1], scale=alt.Scale(zero=False)),
    color="pred"
)

alt.Chart(...)

In [45]:
df_sim2["pred"] = clf.predict(df_sim2)

In [46]:
len(df_sim2)

6300

In [47]:
df_sim2_sub = df_sim2.sample(5000)

In [48]:
df_sim2_sub

bill_length_mm  bill_depth_mm       pred
94              32.4           13.8     Adelie
4312            51.0           20.4  Chinstrap
5119            54.6           19.8  Chinstrap
5339            55.6           18.8  Chinstrap
3207            46.2           15.4     Gentoo
...              ...            ...        ...
856             35.8           13.2     Gentoo
1720            39.6           15.0     Gentoo
2444            42.8           15.8     Gentoo
1481            38.4           21.2     Adelie
5209            55.0           19.8  Chinstrap

[5000 rows x 3 columns]

In [49]:
len(df_sim2_sub)

5000

In [50]:
alt.Chart(df_sim2_sub).mark_circle().encode(
    x=alt.X(cols[0], scale=alt.Scale(zero=False)),
    y=alt.Y(cols[1], scale=alt.Scale(zero=False)),
    color="pred"
)

alt.Chart(...)

## What penguins were misclassified?

<iframe width="560" height="315" src="https://www.youtube.com/embed/XNH3plOaxnw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [51]:
df_sim2

bill_length_mm  bill_depth_mm       pred
0               32.0           13.0     Adelie
1               32.0           13.2     Adelie
2               32.0           13.4     Adelie
3               32.0           13.6     Adelie
4               32.0           13.8     Adelie
...              ...            ...        ...
6295            59.8           21.0  Chinstrap
6296            59.8           21.2  Chinstrap
6297            59.8           21.4  Chinstrap
6298            59.8           21.6  Chinstrap
6299            59.8           21.8  Chinstrap

[6300 rows x 3 columns]

In [52]:
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex    pred  
0         3750.0    Male  Adelie  
1         3800.0  Female  Adelie  
2         3250.0  Female  Adelie  
4         3450.0  Female  Adelie  
5         3650.0    Male  Adelie  
..           ...     ...     ...  
338       4925.0  Female  Gentoo  
340       4850.0  Female  Gentoo  
341       5750.0    Male  Gentoo  
342       5200.0  Female  Gentoo  
343       5400.0    Male  Gentoo  

[333 rows x 8 columns]

In [53]:
df["species"] == df["pred"]

0      True
1      True
2      True
4      True
5      True
       ... 
338    True
340    True
341    True
342    True
343    True
Length: 333, dtype: bool

In [54]:
df["correct"] = (df["species"] == df["pred"])

In [55]:
alt.Chart(df).mark_circle().encode(
    x=alt.X(cols[0], scale=alt.Scale(zero=False)),
    y=alt.Y(cols[1], scale=alt.Scale(zero=False)),
    color="pred"
)

alt.Chart(...)

In [56]:
alt.Chart(df).mark_circle().encode(
    x=alt.X(cols[0], scale=alt.Scale(zero=False)),
    y=alt.Y(cols[1], scale=alt.Scale(zero=False)),
    color="correct"
)

alt.Chart(...)

In [57]:
alt.Chart(df).mark_circle().encode(
    x=alt.X(cols[0], scale=alt.Scale(zero=False)),
    y=alt.Y(cols[1], scale=alt.Scale(zero=False)),
    color=alt.condition(alt.datum.correct, alt.value("black"), alt.value("red"))
)

alt.Chart(...)

In [58]:
df.correct.unique()

array([ True, False])

In [61]:
alt.Chart(df).mark_circle().encode(
    x=alt.X(cols[0], scale=alt.Scale(zero=False)),
    y=alt.Y(cols[1], scale=alt.Scale(zero=False)),
    color=alt.Color("correct", scale=alt.Scale(domain=[True, False], range=["black", "red"]))
)

alt.Chart(...)